version: '3'
services:
  pg:
    image: postgres:9.3

  conjur:
    image: cyberark/conjur
    command: server -a cucumber -p 3000
    environment:
      CONJUR_APPLIANCE_URL: http://localhost:3000
      DATABASE_URL: postgres://postgres@pg/postgres
      CONJUR_DATA_KEY: "W0BuL8iTr/7QvtjIluJbrb5LDAnmXzmcpxkqihO3dXA="
    ports:
      - "3000:3000"
    networks:
      - default
    links:
      - pg

  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/conjurinc/ansible-role-conjur/
      - /var/run/docker.sock:/var/run/docker.sock

  conjur_cli:
    image: conjurinc/cli5
    environment:
      CONJUR_APPLIANCE_URL: http://conjur:3000
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: admin
    volumes:
      - ./policy:/src/policy
      - .:/root
    links:
      - conjur

  myapp_staging:
    build: ./test_app
    entrypoint: sleep
    command: infinity
    ports:
      - 4567
    environment:
      ENV: staging

  myapp_production:
    build: ./test_app
    entrypoint: sleep
    command: infinity
    ports:
      - 4567
    environment:
      ENV: production

  conjur-proxy-nginx:
    build:
     context: .
     dockerfile: Dockerfile_nginx
    entrypoint: nginx-debug -g 'daemon off;'
    environment:
      TERM: xterm
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - conjur
      - conjur_cli
