- hosts: myapp-{{ lookup('env', 'APP_ENV') }}
  vars:
    app_environment: "{{ lookup('env', 'APP_ENV') }}"
  roles:
    - role: configure-conjur-identity
      conjur_account: cucumber
      conjur_appliance_url: "https://conjur-proxy-nginx"
      conjur_host_factory_token: "{{lookup('env', 'HFTOKEN')}}"
      conjur_host_name: "conjur_{{ ansible_hostname }}"
      conjur_ssl_certificate: "{{lookup('file', '/conjurinc/ansible-role-conjur/conjur.pem')}}"
      conjur_validate_certs: yes

  tasks:

    - name: Stop application service
      service: name={{ ansible_env.APP_NAME }} state=stopped

    - name: Install summon-conjur
      shell: "/usr/local/lib/summon/summon-conjur -v | grep $(curl -s https://api.github.com/repos/cyberark/summon/releases/latest | grep -o '\"tag_name\": \"[^\"]*' | grep -o '[^v\"]*$') || curl -sSL https://raw.githubusercontent.com/cyberark/summon-conjur/master/install.sh | bash"

    - name: Copy summon in
      copy: src={{item}} dest=/usr/local/bin mode=+x
      with_first_found:
        - files:
            - /conjurinc/ansible-role-conjur/summon
          skip: true

    - name: Start application service with secrets from Conjur retrieved via summon
      service: name={{ ansible_env.APP_NAME }} state=started
