- hosts: myapp-{{ lookup('env', 'APP_ENV') }}
  vars:
    app_environment: "{{ lookup('env', 'APP_ENV') }}"

  tasks:
    - name: Restart application service with secrets from Conjur retrieved via summon
      service: name={{ ansible_env.APP_NAME }} state=restarted
