- hosts: myapp-{{ lookup('env', 'APP_ENV') }}
  vars:
    app_environment: "{{ lookup('env', 'APP_ENV') }}"
  roles:
    - role: configure-conjur-identity
      conjur_account: cucumber
      conjur_appliance_url: "https://conjur-proxy-nginx"
      conjur_host_factory_token: "{{lookup('env', 'HFTOKEN')}}"
      conjur_host_name: "conjur_{{ ansible_hostname }}"
      conjur_ssl_certificate: "{{lookup('file', '/conjurinc/ansible-role-conjur/conjur.pem')}}"
      conjur_validate_certs: yes

  tasks:
    - name: Find current running Application process
      shell: pgrep ruby || true
      register: current_application_process

    - name: Stop application server (if running)
      shell: kill -9 {{current_application_process.stdout}}
      when: current_application_process.stdout != ''

    - name: Install summon and summon-conjur
      shell: curl -sSL https://raw.githubusercontent.com/cyberark/summon-conjur/master/install.sh | bash; curl -sSL https://raw.githubusercontent.com/cyberark/summon/master/install.sh | bash;

    - name: Start application with secrets from Conjur
      shell: summon -D ENV={{app_environment}} rackup -p 4567 --host 0.0.0.0 -D
